In [1]:
arr = np.ones((3, 3))


NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
arr = np.ones((3, 3))

In [4]:
arr


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr = np.full((2, 3), 7)

In [6]:
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [7]:
arr = np.arange(1, 10, 2)

In [8]:
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.arange(1, 10, 3)

In [10]:
arr


array([1, 4, 7])

In [11]:
arr = np.arange(1, 10, 0)

ZeroDivisionError: division by zero

In [12]:
arr = np.arange(1, 10, -1)

In [13]:
arr


array([], dtype=int64)

In [14]:
arr = np.arange(1, 10, 1)

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1, 4, 1)

array([1.])

In [18]:
np.linspace(1, 4, 2)

array([1., 4.])

In [19]:
np.linspace(1, 4, 10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [20]:
np.eye(1)

array([[1.]])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.random.rand(2,2)

array([[0.55685653, 0.29328188],
       [0.84185315, 0.13303515]])

In [25]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.reshape(arr, (1,2))

ValueError: cannot reshape array of size 9 into shape (1,2)

In [31]:
arr.reshape((1,2))

ValueError: cannot reshape array of size 9 into shape (1,2)

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])


In [33]:
reshaped = arr.reshape((2, 3))

In [34]:
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr


array([1, 2, 3, 4, 5, 6])

In [36]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

In [37]:
np.transpose(arr)

array([1, 2, 3, 4, 5, 6])

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [40]:
arr = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])

In [41]:
arr


array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [42]:
np.transpose(arr)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [43]:
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [44]:
arr.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [45]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [46]:
result = np.concatenate((a, b), axis=0)

In [47]:
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
result = np.concatenate((a, b), axis=1)

In [50]:
result

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [52]:
result = np.split(a, 4)

In [53]:
result

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [54]:
result = np.split(a, 3)

ValueError: array split does not result in an equal division

In [55]:
result = np.split(a, 2)

In [56]:
result

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.add(a, b)

In [58]:
result

array([5, 7, 9])

In [59]:
np.power(a, b)

array([  1,  32, 729])

In [60]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = np.sum(a, axis=0)

In [61]:
result

array([12, 15, 18])

In [62]:
result = np.sum(a, axis=1)

In [63]:
result

array([ 6, 15, 24])

In [64]:
a = np.array([[1, 2], [3, 4]])


In [65]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [67]:
np.random.seed(42)

In [68]:
np.random.rand(5)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [69]:
np.random.rand(5,2)


array([[0.15599452, 0.05808361],
       [0.86617615, 0.60111501],
       [0.70807258, 0.02058449],
       [0.96990985, 0.83244264],
       [0.21233911, 0.18182497]])

In [70]:
np.random.randn(5,2)

array([[-0.57138017, -0.92408284],
       [-2.61254901,  0.95036968],
       [ 0.81644508, -1.523876  ],
       [-0.42804606, -0.74240684],
       [-0.7033438 , -2.13962066]])

In [71]:
random_integers = np.random.randint(0, 10, (2, 3)) 


In [72]:
random_integers

array([[2, 6, 3],
       [8, 2, 4]])

In [73]:
random_integers

array([[2, 6, 3],
       [8, 2, 4]])

In [74]:
choices = np.random.choice([1, 2, 3, 4, 5], size=3)

In [75]:
choices



array([3, 5, 1])

In [76]:
choices_with_replacement = np.random.choice([1, 2, 3, 4, 5], size=5, replace=True)


In [77]:
choices_with_replacement

array([2, 4, 1, 4, 2])

In [78]:
arr = np.array([1, 2, 3])
np.save('array.npy', arr)
loaded = np.load('array.npy')
 


In [79]:
loaded

array([1, 2, 3])

In [80]:
arr = np.array([1, 2, 3, 4, 5])

In [81]:
np.save('array_file.npy', arr)

In [82]:
loaded_array = np.load('/Users/umwelt.ai/Desktop/pandas/array_file.npy')

In [83]:
loaded_array

array([1, 2, 3, 4, 5])

In [84]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [85]:
np.savetxt('array_file.txt', arr, delimiter=' ')

In [87]:
arr = np.array([[11, 21, 3], [44, 5, 6], [76, 8, 9]])
np.savetxt('array_file3.txt', arr, delimiter=' ')
